query MyQuery {
  pages(where: { title: "services" }) {
    edges {
      node {
        serviceCardStyle13 {
          cardStyle13ServiceColumn {
            cardStyle13Heading
            cardStyle13Description
            cardStyle13Image {
              sourceUrl
            }
          }
        }
      }
    }
  }
}
