{
  reviews {
    edges {
      node {
        reviewCardStyle12 {
          reviewBoxCardStyle12 {
            alphaRatingCardStyle12
            circleRangeCardStyle12
            ratingNumberCardStyle12
          }
        }
      }
    }
  }
}
