{
  reviews {
    edges {
      node {
        reviewCardStyle8 {
          reviewBoxCardStyle8 {
            descriptionCardStyle8
            titleCardStyle8
            listItemsCardStyle8 {
              itemCardStyle8
              ratingNumberCardStyle8
            }
          }
        }
      }
    }
  }
}
