query MyQuery {
  pages(where: {title: "header"}) {
    edges {
      node {
        headerStyle1 {
          headerBgImg {
            altText
            sourceUrl
          }
        }
      }
    }
  }
}